--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-08-2021   
--------------------------------------------------------
REM INSERTING into CHAT_LOCATEL.CHAT_CATEGORIAS
SET DEFINE OFF;
delete from CHAT_LOCATEL.CHAT_AYUDA;
delete from CHAT_LOCATEL.CHAT_CATEGORIAS;
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (1,'Reportes',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (2,'Servicios Integrales',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (3,'Informativos',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (4,'Paginas WEB',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (6,'Registro Animal',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (7,'Mit',0,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (8,'Script Llamada de Emergencias',1,4);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (5,'Frases de Uso Común',1,1);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (9,'Presuntos Responsables',1,4);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (10,'Afectados o Lesionados',1,4);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (11,'CDMXContigo',1,3);
Insert into CHAT_LOCATEL.CHAT_CATEGORIAS (ID_CATEGORIA,DESCRIPCION,STATUS,ID_INSTITUCION) values (12,'HOY NO CIRCULA COVID 19',0,1);
